deployments:
  - name: discovery-operator
    containers:
      - name: discovery-operator
        small:
          limits:
            cpu: 50m
            memory: 75Mi
          requests:
            cpu: 1m
            memory: 20Mi
        medium:
          limits:
            cpu: 500m
            memory: 750Mi
          requests:
            cpu: 10m
            memory: 200Mi